# Network
GLIMPSE: 4
HIDDEN_SIZE: 1024
K_TIMES: 3
DROPOUT_R: 0.2
CLASSIFER_DROPOUT_R: 0.5
FLAT_OUT_SIZE: 2048

# Execution
BATCH_SIZE: 512
LR_BASE: 0.002
LR_DECAY_R: 0.25
LR_DECAY_LIST: [10, 13]
WARMUP_EPOCH: 4
MAX_EPOCH: 15
GRAD_NORM_CLIP: 0.25
GRAD_ACCU_STEPS: 8
OPT: Adamax
OPT_PARAMS: {betas: '(0.9, 0.999)', eps: '1e-9'}
